$('.l-off').mouseenter(
  function(){
    $('.l-hover').removeClass('hide')
  }
)
$('.l-off').mouseleave(
  function(){
    $('.l-hover').addClass('hide')
  }
)

$('.z-off').mouseenter(
  function(){
    $('.z-hover').removeClass('hide')
  }
)
$('.z-off').mouseleave(
  function(){
    $('.z-hover').addClass('hide')
  }
)

$('.n-off').mouseenter(
  function(){
    $('.n-hover').removeClass('hide')
  }
)
$('.n-off').mouseleave(
  function(){
    $('.n-hover').addClass('hide')
  }
)

$('.u-off').mouseenter(
  function(){
    $('.u-hover').removeClass('hide')
  }
)
$('.u-off').mouseleave(
  function(){
    $('.u-hover').addClass('hide')
  }
)